-- Canonical music asset schema entrypoint.
--
-- The standalone `music_assets` table has been folded into the production
-- database architecture because it depends on upload batches, storage files,
-- songs, validation reports, duplicate reports, and cloud upload records.
--
-- Run the full production migration instead:
--   supabase/migrations/001_initial_schema.sql
--
-- If you use the Supabase SQL Editor, paste the full migration file there.
-- If you use the Supabase CLI, run:
--   supabase db push
